apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  labels:
    app: metricbeat
data:
  metricbeat.yml: |
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: "elastic"
      password: "elasticstack"
    setup.kibana:
      host: "kibana:5601"
