apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    app: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: elastic/metricbeat:7.7.0
        args: ["-e"]
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "elasticstack"
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
        - name: data
          mountPath: /usr/share/metricbeat/data
      volumes:
      - name: config
        configMap:
          name: metricbeat-config
      - name: data
        emptyDir: {}