- name: Copy Docker GPG key (offline)
  copy:
    src: "files/gpg/docker.gpg"
    dest: "/etc/apt/keyrings/docker.gpg"
    mode: '0644'
  become: true

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch={{ docker_arch | trim }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable
    state: present

- name: Copy Kubernetes apt keyring (offline)
  copy:
    src: "files/gpg/v{{ kubernetes_version }}/Release.key"
    dest: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    mode: '0644'
  become: true

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present