- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename

- name: Set Docker arch fact
  set_fact:
    docker_arch: >-
      {% if ansible_architecture == 'x86_64' %}
        amd64
      {% elif ansible_architecture == 'aarch64' %}
        arm64
      {% else %}
        {{ ansible_architecture }}
      {% endif %}

- name: Add gpg key for Docker repository and Kubernetes apt repository From Online
  when: use_nexus is not defined or use_nexus == false
  import_tasks:
    file: gpg_online_install.yaml

- name: Add gpg key for Docker repository and Kubernetes apt repository From Offline
  when: use_nexus is defined and use_nexus == true
  import_tasks:
    file: gpg_offline_install.yaml

- name: Install containerd and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - containerd.io
  notify:
    - docker status

- name: Disable swap
  command: swapoff -a
  become: true

- name: Remove swap entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s)'
    replace: '#\1'
  become: true

- name: Enable and restart Containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages at current version
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
    allow_unauthenticated: yes
    force: yes
    autoremove: no
    install_recommends: no
    dpkg_options: "--force-confdef --force-confold"
  register: kubernetes_install

- name: Mark Kubernetes packages on hold
  become: true
  shell: |
    apt-mark hold kubelet kubeadm kubectl

- name: Ensure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl params for Kubernetes networking
  sysctl: 
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Set sysctl params for IPv6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes