apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.9.0=quay.io/strimzi/kafka:0.46.0-kafka-3.9.0
                4.0.0=quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.9.0=quay.io/strimzi/kafka:0.46.0-kafka-3.9.0
                4.0.0=quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.9.0=quay.io/strimzi/kafka:0.46.0-kafka-3.9.0
                4.0.0=quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.46.0
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.46.0
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator:0.46.0
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge:0.32.0
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor:0.46.0
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder:0.46.0