- name: strimzi kafka manifest 생성
  hosts: k8s_master_1
  become: yes
  roles:
    - k8s_application/strimzi_kafka



- name: strimzi kafka manifest 적용
  hosts: k8s_master_1
  gather_facts: false
  tasks:
    - name: strimzi kafka manifest 적용
      include_role: 
        name: k8s_application/strimzi_kafka
        tasks_from: apply_manifest.yaml
  