- name: k8s 워커 노드 설치 
  hosts: k8s_worker
  become: yes
  gather_facts: yes
  roles:
    - k8s_install/k8s_common_install
    - k8s_install/kubeadm_join
  vars:
    kubernetes_version: "1.33"
    k8s_install_version_semver: "v1.33.0"