apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: elasticsearch-http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-https
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  clusterIP: None