apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elk

resources:
  - ../base

images:
  - name: elastic/elasticsearch
    newName: elastic/elasticsearch
    newTag: 7.7.0
  - name: elastic/kibana
    newName: elastic/kibana
    newTag: 7.7.0
  - name: elastic/metricbeat
    newName: elastic/metricbeat
    newTag: 7.7.0
